### ISSUE TITLE
Setting `rethink.save=false` still connects to DB

### ISSUE THREAD

**Issue by abitrolly** [cyberFund/xchange-crawler#39]
For testing, there should be a way to run crawler without DB connection. Setting `rethink.save=false` still makes it fail:

```
2017-06-16 19:26:05, ERROR, org.springframework.web.context.ContextLoader, [main] Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'rethinkDbService' defined in URL [jar:file:/cyberapp/xchange-crawler.
jar!/fund/cyber/xchange/service/RethinkDbService.class]: Invocation of init method failed; nested exception is com.rethinkdb.gen.exc.ReqlDriverError: Connect
ion timed out.
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1628) ~[xchange-crawler.jar:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[xchange-crawler.jar:na]
```

**Comment by litvintech** [comment]
```
boolean elastic = config.getProperty("elastic.save").equals("true");
boolean rethink = config.getProperty("rethink.save").equals("true");
```
only checks config to write configuration to write, need to add running mode which allows run app without dbs initializing
